# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

before_script:
  - java -version
  - echo PATH=$PATH
  - echo JAVA_HOME=$JAVA_HOME
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo R CMD javareconf ; fi

matrix:
  include:
  - r: devel
  - r: release
    after_success: Rscript -e 'covr::codecov()'
#    before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
#    deploy:
#      provider: script
#      script: Rscript -e 'pkgdown::deploy_site_github()'
#      skip_cleanup: true
  - r: release
    os: osx
  - r: oldrel
  - r: 3.3
  - r: 3.2
  - r: 3.1
