# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

before_install:
  - java -version
  - echo PATH=$PATH
  - echo JAVA_HOME=$JAVA_HOME
  - sudo $(which R) CMD javareconf

matrix:
  include:
  - r: devel
  - r: release
    after_success: Rscript -e 'covr::codecov()'
    before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true
  - r: release
    os: osx
    # only install binaries on osx to avoid issues with rJava source install
    install:
    - R -e 'install.packages("remotes")'
    - R -e 'remotes::install_deps(dep = T, type = "binary")'
  - r: oldrel
  - r: 3.5
  - r: 3.4
  - r: 3.3
